
admin_login_check:
    path: /api/v1/admin/login_check

client_login_check:
    path: /api/v1/client/login_check


client_routes:
    resource: routes/api/v1/client.yaml
    type: yaml
    prefix: /api/v1/client
    name_prefix: client_