
client_routes:
    resource: routes/api/v1/client.yaml
    type: yaml
    prefix: /api/v1/client
    name_prefix: client_

auth_routes:
    resource: routes/api/v1/auth.yaml
    type: yaml
    prefix: /api/v1/auth
    name_prefix: auth_
